video_accesses_by_COs: ~/work/cp-mec/misc/gen-video-acc-reqs-at-central-offices/.output/centraloffice-videoaccesses

utility_curves: ~/work/cp-mec-data/utility-curves/youtube-CO.tar.7z

# Skip workloads and utility curves that are over max_co_id (max CO ID) for saving time during dev.
#   Set to -1 for no limit.
max_co_id: -1
#max_co_id: 100


# Hit ratio of Facebook edge caches
# - Huang et al. - 2013 - An analysis of Facebook photo caching
#cache_hit_ratio: 0.58

# wired_network_rtt_ms_per_km: 0.018038

# OpenSignal network latencies in the USA. 3G and 4G.
#   https://opensignal.com/reports/2016/08/usa/state-of-the-mobile-network/
#
#   Questions:
#     What is the 3G:4G ratio?
#     What do those error bars mean? 25% and 75% percentile?
#     What exactly did they measure? Time to first byte? How big were the requests?
#
# mobile_newtwork_speed:
#   3G:
#     ratio: 0.5
#     # In milliseconds
#     carrier_latency:
#       "AT&T":     124.55
#       "Sprint":   149.95
#       "T-Mobile":  98.91
#       "Verizon":  177.36
#   4G:
#     ratio: 0.5
#     carrier_latency:
#       "AT&T":      64.71
#       "Sprint":    57.06
#       "T-Mobile":  61.55
#       "Verizon":   60.47
