video_accesses_by_COs: ~/work/cp-mec/misc/gen-video-acc-reqs-at-central-offices/.output/centraloffice-videoaccesses

utility_curves: ~/work/cp-mec-data/utility-curves/youtube-CO.tar.7z

# Skip workloads and utility curves that are over max_el_id (max edge location ID) for saving time during dev.
#   Set to -1 for no limit.
#   22978 is the max for now. The utility curve for 22979 is missing.
#max_el_id: -1
max_el_id: 22978
#max_el_id: 1

# linear or exponential
cache_size_increment_type: exponential
#cache_size_increment_type: linear

#convert_utility_curves_to_convex: false
convert_utility_curves_to_convex: true

# uniform, req_volume_based, utility_based
#placement_stragegy: uniform
#placement_stragegy: req_volume_based
#placement_stragegy: user_based
placement_stragegy: utility_based




# The time to get the first byte
#   TODO: For the video streaming, you will need the time to get 1 MB of data from all pairs.
#     The delay will be a part of the video loading time and the time when a user jumps to a random location of the video.
#
# Implementation
#   The average distance between the data request location and an EL.
#     TODO: pre-calculate it.
#     Latency using the average distance should be good enough. Calculating it everytime would take too much time.
#   The distance between an EL to its closest data origin (Use Amazon data center locations).
#     TODO: pre-calculate the numbers.
wired_network_rtt_ms_per_km: 0.018038

lat_4g: 60.9475
# OpenSignal network latencies in the USA. 3G and 4G.
#   https://opensignal.com/reports/2016/08/usa/state-of-the-mobile-network/
#   What is the 3G:4G ratio?
#   What do those error bars mean? 25% and 75% percentile?
#   What exactly did they measure? Time to first byte? How big were the requests?
#
# mobile_newtwork_speed:
#   3G:
#     ratio: 0.5
#     # In milliseconds
#     carrier_latency:
#       "AT&T":     124.55
#       "Sprint":   149.95
#       "T-Mobile":  98.91
#       "Verizon":  177.36
#   4G:
#     ratio: 0.5
#     carrier_latency:
#       "AT&T":      64.71
#       "Sprint":    57.06
#       "T-Mobile":  61.55
#       "Verizon":   60.47
#
# calc "64.71 + 57.06 + 61.55 + 60.47" = 60.9475

# Average network latency between BS to CO. RTT in ms.
lat_bs_to_co: 0.05


# Hit ratio of Facebook edge caches
# - Huang et al. - 2013 - An analysis of Facebook photo caching
#cache_hit_ratio: 0.58
